title: MARS Red
description: The official website for the MARS Red project
theme: just-the-docs

url: https://xarkenz.github.io/mars-red
java_se_docs: https://docs.oracle.com/en/java/javase/17/docs/api

aux_links:
    GitHub Repository: https://github.com/xarkenz/mars-red
    JavaDoc: https://xarkenz.github.io/mars-red/javadoc

callouts:
    note:
        title: Note
        color: blue
    warning:
        title: Warning
        color: yellow

