title: MARS Red
description: The official website for the MARS Red project
theme: just-the-docs

url: https://xarkenz.github.io/mars-red

aux_links:
    GitHub Repository: https://github.com/xarkenz/mars-red
    JavaDoc: https://xarkenz.github.io/mars-red/javadoc
